imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: jms_serializer.yml }
    - { resource: fos_rest.yml }
    - { resource: knp_menu.yml }
    - { resource: knp_paginator.yml }
    - { resource: mopa_bootstrap.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    #translator: ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    # Fcj.2013-08-14 : After upgrade to Symfony 2.2.5, this seems to have been dropped.
    #trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ 'MopaBootstrapBundle' ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

        ## Fcj.2013-07-02 : Doing so along setting up MopaBootstrapBundle.
        less:
            node: /usr/bin/node
            node_paths: [ /usr/lib/node_modules ]
            apply_to: "\.less$"

        ## Fcj.2013-07-02 : Adding these c/o for some later day wanderings (MopaBootstrapBundle).
        ## @see https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/doc/assetic-configuration.md
        #cssembed:
        #    jar: %kernel.root_dir%/Resources/java/cssembed-0.3.6.jar
        #    apply_to: "\.css$|\.less$"
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
        #    apply_to: "\.css$"
        #yui_js:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar


# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        #path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# Copy-pasted from https://github.com/simplethings/EntityAudit#installation-in-symfony2-application
simple_things_entity_audit:
    audited_entities: ~
#    audited_entities:
#        - MyBundle\Entity\MyEntity
#        - MyBundle\Entity\MyEntity2
