imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com

# WebProfilerExtraBundle
# Copy-pasted and commented-out (seems to be the defaults) from :
#    https://github.com/Elao/WebProfilerExtraBundle
#web_profiler_extra:
#    routing:
#        enabled:        true
#        display_in_wdt: true
#    container:
#        enabled:        true
#        display_in_wdt: true
#    assetic:
#        enabled:        true
#        display_in_wdt: true
#    twig:
#        enabled:        true
#        display_in_wdt: true

# JMSDebuggingBundle
# See http://jmsyst.com/bundles/JMSDebuggingBundle
#jms_debugging:
    # You can set this to true if you want to automatically retrieve help
    # messages for public exceptions. If you leave this set to false, you have
    # to click the "search" button manually each time.
#    auto_help: true
