# app/config/routing.yml

# FOSJsRoutingBundle
# See https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/master/Resources/doc/README.markdown
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

#fcj_dummy:
#    resource: "@FcjDummyBundle/Resources/config/routing.yml"
#    prefix:   /

#fcj_node:
#    #resource: "@FcjNodeBundle/Controller/"
#    #type:     annotation
#    resource: "@FcjNodeBundle/Resources/config/routing.yml"
#    prefix:   /_node

fcj_form:
    resource: "@FcjFormBundle/Resources/config/routing.yml"
    prefix:   /
