<?php

namespace Fcj\FormBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FormSpecRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormSpecRepository extends EntityRepository
{

    /**
     * @param $name string FormSpec::name
     * @return FormSpec
     */
    public function findByName ($name)
    {
        return $this->findOneBy(array('name'=>$name));
    }

    /// ===============================================================
    // hummm maybe not here...
    //public function newFormFromSpec($name)    {}
}
